# configure for uclinux
# before run this file, apply the patches/configure-fix-arm-elf-build.patch to
# make configure script pass the check for:
#   "C compiler cannot create executables"
# dont's add cflags "-nostartfiles" else we'll get SIGSEGV!
#

CC=arm-elf-gcc \
CFLAGS="-I/home/wucan/workdir/x/xmux/extern-arm-libs/net-snmp/include -D_UCLINUX_ -O2 -g -fomit-frame-pointer   -Dlinux -D__linux__ -Dunix -D__uClinux__ -DEMBED -I/home/wucan/workdir/x/snapgear/lib/uClibc/include -I/home/wucan/workdir/x/snapgear/lib/libm -I/home/wucan/workdir/x/snapgear/lib/libcrypt_old -I/home/wucan/workdir/x/snapgear -fno-builtin -nostartfiles -I/home/wucan/workdir/x/snapgear/linux-2.4.x/include" \
LDFLAGS="-L/home/wucan/workdir/x/xmux/net-snmp-lib/lib/ -O2 -g -fomit-frame-pointer   -Dlinux -D__linux__ -Dunix -D__uClinux__ -DEMBED -I/home/wucan/workdir/x/snapgear/lib/uClibc/include -I/home/wucan/workdir/x/snapgear/lib/libm -I/home/wucan/workdir/x/snapgear/lib/libcrypt_old -I/home/wucan/workdir/x/snapgear -fno-builtin -nostartfiles -I/home/wucan/workdir/x/snapgear/linux-2.4.x/include -Wl,-elf2flt  -L/home/wucan/workdir/x/snapgear/lib/uClibc/. -L/home/wucan/workdir/x/snapgear/lib/uClibc/lib -L/home/wucan/workdir/x/snapgear/lib/libm -L/home/wucan/workdir/x/snapgear/lib/libnet -L/home/wucan/workdir/x/snapgear/lib/libdes -L/home/wucan/workdir/x/snapgear/lib/libaes -L/home/wucan/workdir/x/snapgear/lib/libpcap -L/home/wucan/workdir/x/snapgear/lib/libcrypt_old -L/home/wucan/workdir/x/snapgear/lib/libssl -L/home/wucan/workdir/x/snapgear/lib/zlib -L/home/wucan/workdir/x/xmux/net-snmp-lib/lib/ -lnetsnmpagent -lnetsnmphelpers  -lnetsnmp  -lpthread" \
./configure --host=i686 --with-build-target=arm

exit 0
CFLAGS="-I/home/wucan/workdir/x/xmux/net-snmp-lib/include -D_UCLINUX_ -fomit-frame-pointer -fno-builtin -nostartfiles -I/home/wucan/workdir/x/snapgear/lib/uClibc/include -I/home/wucan/workdir/x/snapgear/lib/libm -O2" \
LDFLAGS="-L/home/wucan/workdir/x/xmux/net-snmp-lib/lib/ -O2 -g -fomit-frame-pointer   -Dlinux -D__linux__ -Dunix -D__uClinux__ -DEMBED -I/home/wucan/workdir/x/snapgear/lib/uClibc/include -I/home/wucan/workdir/x/snapgear/lib/libm -I/home/wucan/workdir/x/snapgear/lib/libcrypt_old -I/home/wucan/workdir/x/snapgear -fno-builtin -nostartfiles -I/home/wucan/workdir/x/snapgear/linux-2.4.x/include -Wl,-elf2flt /home/wucan/workdir/x/snapgear/lib/uClibc/lib/crt0.o /home/wucan/workdir/x/snapgear/lib/uClibc/lib/crti.o /home/wucan/workdir/x/snapgear/lib/uClibc/lib/crtn.o -L/home/wucan/workdir/x/snapgear/lib/uClibc/. -L/home/wucan/workdir/x/snapgear/lib/uClibc/lib -L/home/wucan/workdir/x/snapgear/lib/libm -L/home/wucan/workdir/x/snapgear/lib/libnet -L/home/wucan/workdir/x/snapgear/lib/libdes -L/home/wucan/workdir/x/snapgear/lib/libaes -L/home/wucan/workdir/x/snapgear/lib/libpcap -L/home/wucan/workdir/x/snapgear/lib/libcrypt_old -L/home/wucan/workdir/x/snapgear/lib/libssl -L/home/wucan/workdir/x/snapgear/lib/zlib -L/home/wucan/workdir/x/xmux/net-snmp-lib/lib/ -lnetsnmpagent -lnetsnmpmibs -lnetsnmphelpers  -lnetsnmp  -lpthread" \
./configure --host=i686 --with-build-target=arm

LDFLAGS="-L/home/wucan/workdir/x/xmux/net-snmp-lib/lib/ -O2 -g -fomit-frame-pointer   -Dlinux -D__linux__ -Dunix -D__uClinux__ -DEMBED -I/home/wucan/workdir/x/snapgear/lib/uClibc/include -I/home/wucan/workdir/x/snapgear/lib/libm -I/home/wucan/workdir/x/snapgear/lib/libcrypt_old -I/home/wucan/workdir/x/snapgear -fno-builtin -nostartfiles -I/home/wucan/workdir/x/snapgear/linux-2.4.x/include -Wl,-elf2flt  -L/home/wucan/workdir/x/snapgear/lib/uClibc/. -L/home/wucan/workdir/x/snapgear/lib/uClibc/lib -L/home/wucan/workdir/x/snapgear/lib/libm -L/home/wucan/workdir/x/snapgear/lib/libnet -L/home/wucan/workdir/x/snapgear/lib/libdes -L/home/wucan/workdir/x/snapgear/lib/libaes -L/home/wucan/workdir/x/snapgear/lib/libpcap -L/home/wucan/workdir/x/snapgear/lib/libcrypt_old -L/home/wucan/workdir/x/snapgear/lib/libssl -L/home/wucan/workdir/x/snapgear/lib/zlib -L/home/wucan/workdir/x/xmux/net-snmp-lib/lib/ -lnetsnmpagent -lnetsnmpmibs -lnetsnmphelpers  -lnetsnmp  -lpthread" \
